---
# tasks file for rabbitmq
- name: YUM Repos from the script provided by vendor.
  ansible.builtin.shell: "{{item}}"
  loop:
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

- name: Install RabbitMQ
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: This task is to Start & Enable rabbitmq Service
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

# - name: add_user
#   ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

# - name: set_permissions 
#   ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
  
- name: create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present