- name: This task is to check user roboshop
  ansible.builtin.command: id roboshop
  register: output
  ignore_errors: true  

- name: This task is to add user roboshop
  ansible.builtin.user:
    name: roboshop
  when: output.rc != 0

- name: This task is to check app directory
  ansible.builtin.stat:
    path: /app
  register: status

- name: This task is to display app directory
  ansible.builtin.debug:
    msg: "ouput : {{status}}"

- name: This task is to create app directory
  ansible.builtin.file:
    path: /app
    state: directory
  when: status.stat.exists == False

- name: This task is to download the application code to created app directory.
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp

- name: This task is to unzip
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes