- name: This task is to copy the mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: This task is to Install MongoDB shell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: This task is to load schemas of {{component}}
  ansible.builtin.shell: mongo --host mongodb.padmasrikanth.tech < /app/schema/{{component}}.js