- name: install mysql client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql.padmasrikanth.tech -uroot -pRoboShop@1 < /app/schema/{{component}}.sql