- name: This task is to Load the service.
  ansible.builtin.systemd:
    daemon_reload: true

- name: This task is to Start & Enable {{component}} Service
  ansible.builtin.service:
    name: "{{component}}"
    state: started
    enabled: yes