---
# tasks file for mysql
- name: disable mysql
  ansible.builtin.shell: "yum module disable mysql -y"

- name: This task is to copy the mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: This task is to Start & Enable mysql Service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Use password RoboShop@1 or any other as per your choice.
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1